#!/bin/bash
# Script simplificado para obter Chat ID de um grupo do Telegram
# Método mais fácil: usar o bot @RawDataBot

echo "📱 COMO OBTER O CHAT ID DE UM GRUPO DO TELEGRAM"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🎯 MÉTODO MAIS FÁCIL (RECOMENDADO):"
echo ""
echo "1️⃣  Abra o Telegram e vá para o grupo"
echo "2️⃣  Adicione o bot @RawDataBot ao grupo"
echo "3️⃣  O bot automaticamente enviará uma mensagem com todas as informações"
echo "4️⃣  Procure na mensagem por: \"id\": -1001234567890"
echo "5️⃣  O número negativo é o Chat ID do grupo"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🔍 MÉTODO ALTERNATIVO - Verificar Logs do Webhook:"
echo ""
echo "1️⃣  Envie uma mensagem no grupo (pode ser qualquer coisa)"
echo "2️⃣  Execute: ./ver_logs_vinculacao.sh"
echo "3️⃣  Procure por 'chat_id' ou 'chat.id' nos logs"
echo "4️⃣  O valor será algo como: -1001234567890"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 MÉTODO ALTERNATIVO - Usar Bot Auxiliar:"
echo ""
echo "Bots úteis que mostram Chat IDs:"
echo "   • @RawDataBot - Mostra todas as informações do grupo"
echo "   • @userinfobot - Mostra informações do chat atual"
echo "   • @getidsbot - Mostra IDs de usuários e grupos"
echo "   • @chatid_robot - Especializado em mostrar Chat IDs"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "💡 DICA:"
echo ""
echo "Chat IDs de grupos são sempre números NEGATIVOS:"
echo "   • Grupos normais: -123456789"
echo "   • Supergrupos: -1001234567890 (começam com -100)"
echo "   • Canais: -1001234567890 (começam com -100)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "❓ Precisa de ajuda? Execute:"
echo "   ./obter_info_grupo_telegram.sh -1001234567890"
echo "   (Substitua -1001234567890 pelo ID que você suspeita)"
echo ""
